# Generated by Django 5.0.6 on 2024-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course/img/default.jpg', null=True, upload_to='course/course_pic/'),
        ),
    ]
