# Generated by Django 5.0.6 on 2024-08-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_instructor_image_alter_student_image'),
        ('course', '0008_deposit_enrollment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposit',
            new_name='Balance',
        ),
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Enroll',
        ),
    ]
