# Generated by Django 5.0.6 on 2024-07-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_instructor_image_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
